imports:
    - php

filter:
    paths:[app/src/Dbtables/*]
    excluded_paths: [vendor/*, test/*,unitests/*,roka/*,coverage/*]

tools:
    external_code_coverage:
        timeout: 600 # Timeout in seconds.
